### PR TITLE
Bump Qt to 5.15.2

### PR DESCRIPTION
**Pull request by signedav**

### CODE REVIEW

**Comment by m-kuhn** [comment]
That will also give us pointcloud support I guess

**Review by m-kuhn — APPROVED** [review]
Code looks good
Let's see if it works for a qfield build

**Comment by signedav** [comment]
Building https://github.com/opengisch/QField/pull/1479

If okay, I'll merge and make a release.

**Comment by suricactus** [comment]
What are the consequences if I don't update to 5.15.2 locally on my machine? I am already using 5.15.1 for a few months.

**Pull request merged**
