### PR TITLE
Disabled hdf5 module

### PR DESCRIPTION
**Pull request by sklencar**
Hdf5 module has been causing a build issue for current QGIS 3.3.0. Therefore -`DCMAKE_DISABLE_FIND_PACKAGE_HDF5=TRUE` has been added to qgis recipe.sh.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Interesting, is there more information on this build issue?

**Comment by PeterPetrik** [comment]
@m-kuhn it is because MDAL now optionally depends on HDF5 (https://github.com/qgis/QGIS/blob/master/external/mdal/frmts/mdal_hdf5.hpp).

**Comment by m-kuhn** [comment]
This script here

https://gist.github.com/m-kuhn/9be250c5b0a4d03703f10045832e27c8

It builds master from a couple of days ago with an additional patch (for an error with qgsnative lib) which has been merged back meanwhile

**Comment by PeterPetrik** [comment]
dont know, for some reason @sklencar doesn't have hdf5 crosscompiled, and you have

**Comment by m-kuhn** [comment]
Sounds a bit too much like black magic, I cross-compiled only with scripts. I'll check if I have sync'd back everything to master.

**Comment by m-kuhn** [comment]
Please try again with #23

**Comment by PeterPetrik** [comment]
@m-kuhn we are still unable to compile without disabling HDF5 with error 

```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at /usr/share/cmake-3.9/Modules/FindHDF5.cmake:196 (try_compile):
Failed to configure test project build system.
Call Stack (most recent call first):
/usr/share/cmake-3.9/Modules/FindHDF5.cmake:484 (_HDF5_test_regular_compiler_C)
src/providers/mdal/CMakeLists.txt:20 (FIND_PACKAGE)
```

My guess is that in your build (docker?), you do not have `libhdf5-dev` linux (native) package installed. So FindHDF5 will quit sooner since there are no hdf5 headers on include path at all? 

Would it be possible to check in the generated build system if you have HDF5-FOUND set to false or true?

**Comment by m-kuhn** [comment]
Good guess.
But then the followup question would be, why it looks on the native include path, that sounds dangerous (but the `distribute.sh` files actually does have some nasty dangerous hacks).

**Comment by PeterPetrik** [comment]
hmm, was it just a statement or should we do something else here for this PR :) ?

**Comment by m-kuhn** [comment]
Nah, let's just merge it, it doesn't hurt. At least we have all the information in here now, in case someone wonders in the future why this was added ;P

**Pull request merged**
