### PR TITLE
fixes to allow compilation of android binaries on MacOS High Sierra

### PR DESCRIPTION
**Pull request by PeterPetrik**
Was able to successfully build a test application on MacOS and deploy on my android tablet.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks!
I think it's best if @3nids has a look here

**Comment by PeterPetrik** [comment]
@3nids thanks for the review, typo fixed

**Comment by 3nids** [comment]
manually merged in 7e8f409  
(not a huge fan of merge commits, better do rebase on top of master)
thanks for this!

**Comment by PeterPetrik** [comment]
@3nids sorry for that, I used the github browser feature to resolve conflicts, wasn't sure what it does internally.

**Pull request closed without merging**
