### PR TITLE
Update QGIS to latest master revision

### PR DESCRIPTION
**Pull request by nirvn**
Needed to finish oauth2 support in QField.

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , the build errors out with QGIS, some python cmake error. Could this be a regression from https://github.com/qgis/QGIS/commit/555f5169254a2278b6aa03d3be9dc93bbf75d35b#diff-251d177e3e7db921c05d14a06c2495601e4bb0e8ccfff429ac77fa6cd65786ec ?

**Comment by 3nids** [comment]
maybe, can you try with this patch: https://github.com/3nids/QGIS/commit/d5c9efc840605ecdc556e5f72a74172f80d5bd96

**Comment by nirvn** [comment]
@m-kuhn , this commit ( https://github.com/qgis/QGIS/commit/c205b2705e42547a5846eb16277d89d0209d4bb3 ) broke building of QGIS here.

**Comment by 3nids** [comment]
@nirvn we can potentially make them #if QT_VERSION < 6.0.0 on QGIS source code?

**Comment by nirvn** [comment]
@3nids , we can try.

**Pull request closed without merging**
