### PR TITLE
Bump Qt to 5.15.1

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
@signedav before merging, can you update this PR to the latest 5.15?

**Comment by nirvn** [comment]
@m-kuhn , any big wins out of this update?

**Comment by nirvn** [comment]
Looking at the changelog, this might be interesting:

Android
-  Introduced the use of Android's native file dialog by default for open (file, multiple files, directory) and save operations.

**Comment by signedav** [comment]
@nirvn "to align with ios and (future) windows" (@m-kuhn hope you don't mind when I quote you :slightly_smiling_face: )

**Comment by m-kuhn** [comment]
> Introduced the use of Android's native file dialog by default for open (file, multiple files, directory) and save operations.

That is very interesting !

**Pull request closed without merging**
