### PR TITLE
Add support for Android NDK 12

### PR DESCRIPTION
**Pull request by wonder-sk**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @wonder-sk Happy to merge if it helps.
In the future we will need to switch to clang. gcc has been deprecated in the ndk and Qt 5.7 no longer compiles (requires C++11).

**Comment by wonder-sk** [comment]
I have few more changes in recipes pending... stay tuned :-)

**Comment by wonder-sk** [comment]
By the way, how do you mean Qt 5.7 no longer compiles with gcc? Qt project ships 5.7 for armv7 and if I understand correctly it is built with g++

**Comment by m-kuhn** [comment]
I didn't manage with a quick test (errored out on C++11 features), I think the gcc version shipped with the NDK is just very, very old.

**Comment by wonder-sk** [comment]
Got such problem too, but it's obviously just something dodgy with Qt5.7 vs cmake.

How to fix it - in Qt/5.7/android_armv7/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake

Replace this line:
```
set_property(TARGET Qt5::Core PROPERTY INTERFACE_COMPILE_FEATURES cxx_decltype)
```
By this one:
```
set(CMAKE_CXX_STANDARD 14)
```

https://bugreports.qt.io/browse/QTBUG-54666
http://public.kitware.com/pipermail/cmake-developers/2016-July/029005.html

**Comment by m-kuhn** [comment]
Thanks for the hint, will try next week!

**Comment by wonder-sk** [comment]
@m-kuhn Ready to me merged... everything builds for me (NDK 12 + Qt 5.7 with the patch above)

**Comment by m-kuhn** [comment]
Nice!
I wonder if this could be integrated in the android.toolchain file so it
would work with a vanilla Qt 5.7 SDK.

**Comment by wonder-sk** [comment]
Hmmm I don't really dare to try that: 1. it is something deep inside Qt5's cmake config, 2. it may just go away with a different combination of cmake/qt versions 3. android.toolchain should be generic config without special Qt stuff

**Comment by m-kuhn** [comment]
android.toolchain is a collection of hacks and poorly implemented, there
are a zillion of different versions out there (see e.g.
https://github.com/taka-no-me/android-cmake/issues/81#issuecomment-229829753).
If there's anything at all that can be done, I don't mind at all.

**Comment by m-kuhn** [comment]
Thanks, good stuff!

Were you able to compile QGIS as well? I had trouble with the GCC version check [here](https://github.com/qgis/QGIS/blob/master/CMakeLists.txt#L350) which failed so it was compiled without C++11 but it worked if I removed the check (and I wonder if we could just require C++11 on QGIS anyway to "fix" this).

**Comment by wonder-sk** [comment]
Yeah QGIS 2.14 compiled just fine for me - I didn't encounter any problem with GCC version check...

**Pull request merged**
